#
# Module manifest for module 'Azure AD Support Manifest'
#
# Generated by: William Fiddes
#
# Generated on: 4/30/2019
#

@{

# Script module or binary module file associated with this manifest
RootModule = '.\_RootModuleShared.psm1'

# Version number of this module.
<<<<<<< HEAD:AadSupport.psd1
ModuleVersion = '0.4.0'
=======
ModuleVersion = '0.3.7'
>>>>>>> df812b2feffde2d1fcf1d9bbbe7f62f63115b552:AadSupportPreview.psd1

# ID used to uniquely identify this module
GUID = '5e5f83b2-7760-43db-aee9-872bf7dfd327'

# Author of this module
Author = 'William Fiddes'

# Company or vendor of this module
CompanyName = 'William Fiddes'

# Copyright statement for this module
Copyright = '(c) 2019 William Fiddes'

# Description of the functionality provided by this module
Description = 'PowerShell module that extends Azure AD support to help diagnose, reproduce, and resolve issues.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @("AzureAdPreview")

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @("_startup.ps1")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    ".\functions\Add-AadConsent.ps1",
    ".\functions\Connect-AadSupport.ps1",
    ".\functions\ConvertFrom-AadJwtTime.ps1",
    ".\functions\ConvertFrom-AadBase64StringToThumbprint.ps1",
    ".\functions\ConvertFrom-AadBase64String.ps1",
    ".\functions\ConvertFrom-AadThumbprintToBase64String.ps1",
    ".\functions\ConvertFrom-AadBase64Certificate.ps1",
    ".\functions\ConvertFrom-AadJwtToken.ps1",
<<<<<<< HEAD:AadSupport.psd1
    ".\functions\ConvertFrom-AadImmutableId.ps1",
=======
>>>>>>> df812b2feffde2d1fcf1d9bbbe7f62f63115b552:AadSupportPreview.psd1
    ".\functions\ConvertTo-AadBase64EncodedString.ps1",
    ".\functions\Import-AadAzureRoleAssignments.ps1",
    ".\functions\Export-AadAzureRoleAssignments.ps1",
    ".\functions\Get-AadAdminRolesByObject.ps1",
    ".\functions\Get-AadAppPermissionInfo.ps1",
    ".\functions\Get-AadApplication.ps1",
    ".\functions\Get-AadAppRolesByObject.ps1",
    ".\functions\Get-AadAzureRoleAssignments.ps1",
    ".\functions\Get-AadDateTime.ps1",
    ".\functions\Get-AadDiscoveryKeys.ps1",
    ".\functions\Get-AadConsent.ps1",
    ".\functions\Get-AadKeyVaultAccessByObject.ps1",
    ".\functions\Get-AadObjectCount.ps1",
    ".\functions\Get-AadOpenIdConnectConfiguration.ps1",
    ".\functions\Get-AadReportMfaEnabled.ps1",
    ".\functions\Get-AadReportMfaEnrolled.ps1",
    ".\functions\Get-AadReportMfaNotEnrolled.ps1",
    ".\functions\Get-AadReportCredentialsExpiringSoon.ps1",
    ".\functions\Get-AadServicePrincipal.ps1",
    ".\functions\Get-AadServicePrincipalAdmins.ps1",
    ".\functions\Get-AadServicePrincipalAccess.ps1",
    ".\functions\Get-AadToken.ps1",
    ".\functions\Get-AadTokenUsingAdal.ps1",
    ".\functions\Get-AadTenantAdmins.ps1",
    ".\functions\Get-AadUserAccess.ps1",
    ".\functions\Get-AadUserInfo.ps1",
    ".\functions\Get-AadUserRealm.ps1",
    ".\functions\Invoke-AadProtectedApi.ps1",
    ".\functions\New-AadClientAssertion.ps1",
    ".\functions\New-AadApplicationCertificate.ps1",
    ".\functions\Set-AadConsent.ps1",
    ".\functions\Revoke-AadConsent.ps1",
    ".\functions\Update-AadSupport.ps1",
    ".\functions\Validate-AadToken.ps1"
)

# Functions to export from this module
FunctionsToExport = '*-Aad*'

# Cmdlets to export from this module
CmdletsToExport = '*-Aad*'

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = '*-Aad*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/ms-willfid/aad-support-psh-module'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}